In [4]:
import numpy as np
import pandas as pd
import zipfile

In [44]:
zipfile_path = '../data/IHS_survey/MWI_2019_IHS-V_v06_M_CSV.zip'

data_folder = '../Data/IHS_survey/'


#open the zip file
with zipfile.ZipFile(zipfile_path, 'r') as z:
    #list the contents of the zip file
    #print(z.namelist())
    
    with z.open('HH_MOD_E.csv') as f:  #Time Use and Labour
        #read the csv 
        df1 = pd.read_csv(f)
        
        print(df1.head(5))

    # with z.open('householdgeovariables_ihs5.csv') as f: #geographic data
    #     #read the csv 
    #     df2 = pd.read_csv(f)
        
    #     print(df2.head(5))

    with z.open('HH_MOD_B.csv') as f: #sex
        #read the csv 
        df3 = pd.read_csv(f)
        
        print(df3.head(5))
    
    with z.open('hh_mod_a_filt.csv') as f: #geographic data  urban/rural
        #read the csv 
        df4 = pd.read_csv(f)
        
        print(df4.head(5))
   
    # with z.open('HH_MOD_B.csv') as f: #household members
    #     #read the csv 
    #     df5 = pd.read_csv(f)
        
    #     print(df5.head(5))

C:\Users\rheredia\AppData\Local\Temp\ipykernel_5588\3075445589.py:13: DtypeWarning: Columns (38,42,44,45,46,64,88,90,92,93,94,95,105,117,122,125,126,133,158) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(f)

        case_id                              HHID  PID hh_e03  hh_e04  hh_e05  \
0  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    1    YES     NaN     0.0
1  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    2    YES     NaN     1.0
2  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    3     NO     2.0     0.0
3  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    4    NaN     NaN     NaN
4  101011000023  7144cc6d29b3485d9e6d6188b255c756    1    YES     NaN     1.0

   hh_e06 hh_e06_1a hh_e06_1b hh_e06_1c  ... hh_e63 hh_e64 hh_e65 hh_e66  \
0     0.0        NO        NO        NO  ...    NaN    NaN    NaN     No
1     0.0       YES        NO        NO  ...    NaN    NaN    NaN     No
2     0.0       YES        NO        NO  ...    NaN    NaN    NaN     No
3     NaN       NaN       NaN       NaN  ...    NaN    NaN    NaN    NaN
4     0.0       YES       YES        NO  ...    NaN    NaN    NaN     No

  hh_e67 hh_e68 hh_e69  hh_e70 hh_e71  hh_e71_oth
0     No    NaN    NaN      No    NaN         NaN
1     No    NaN    NaN     NaN    NaN         NaN
2     No    NaN    NaN     NaN    NaN         NaN
3    NaN    NaN    NaN     NaN    NaN         NaN
4     No    NaN    NaN      No    NaN         NaN

[5 rows x 159 columns]
        case_id                              HHID  PID  hh_b03  \
0  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    1    MALE
1  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    2  FEMALE
2  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    3    MALE
3  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf    4    MALE
4  101011000023  7144cc6d29b3485d9e6d6188b255c756    1  FEMALE

                hh_b04 hh_b04a hh_b05_2 hh_b05_2_1  hh_b05a  hh_b05b  ...  \
0                 HEAD      NO      NaN        NaN       41      NaN  ...
1         WIFE/HUSBAND     YES      NaN        NaN       34      NaN  ...
2  CHILD/ADOPTED CHILD      NO       NO        NaN       11      NaN  ...
3  CHILD/ADOPTED CHILD     NaN      YES        YES        4      8.0  ...
4                 HEAD      NO      NaN        NaN       55      NaN  ...

  hh_b26a  hh_b26a_1  hh_b26b  hh_b26b_1 hh_b26b_2 hh_b26c hh_b26c_1  \
0     2.0     2006.0      NaN        NaN        NO     NaN       NaN
1     1.0     2006.0      NaN        NaN       NaN     NaN       NaN
2     NaN        NaN      NaN        NaN       NaN     NaN       NaN
3     NaN        NaN      NaN        NaN       NaN     NaN       NaN
4     NaN        NaN      NaN        NaN       NaN     NaN       NaN

  hh_b26c_2 hh_b27  hh_b28
0       NaN    YES     1.0
1       NaN    NaN     NaN
2       NaN    NaN     NaN
3       NaN    NaN     NaN
4       NaN    NaN     NaN

[5 rows x 53 columns]
        case_id                              HHID     ea_id region district  \
0  101011000014  7d78f2c5da59436d9bde9b09ea8a8aaf  10101100  North  Chitipa
1  101011000023  7144cc6d29b3485d9e6d6188b255c756  10101100  North  Chitipa
2  101011000040  9936d103bf974a93afbc63d477b8b3f2  10101100  North  Chitipa
3  101011000071  cc8f211413cd493e83e01a96aba95bbb  10101100  North  Chitipa
4  101011000095  e50cfa8d11b44d56891e0fad015b07c7  10101100  North  Chitipa

  reside interviewDate   hh_wgt  hh_a02a  hh_a03  ...  hh_a11 hh_a13 hh_a22  \
0  RURAL    2019-08-29  93.7194    10101     100  ...      NO    NaN     14
1  RURAL    2019-08-29  93.7194    10101     100  ...      NO    NaN     14
2  RURAL    2019-08-28  93.7194    10101     100  ...      NO    NaN     14
3  RURAL    2019-08-29  93.7194    10101     100  ...      NO    NaN     14
4  RURAL    2019-08-28  93.7194    10101     100  ...      NO    NaN     14

   hh_a23  hh_g09 hh_m00 hh_o0a hh_s01 hh_w01 hhsize
0      58      NO    Yes    YES    YES     NO      4
1      64     YES    Yes    YES    YES     NO      4
2      30      NO    Yes     NO     NO     NO      4
3      30      NO    Yes    YES    YES     NO      5
4      58      NO    Yes     NO    YES     NO      5

[5 rows x 21 columns]

C:\Users\rheredia\AppData\Local\Temp\ipykernel_5588\3075445589.py:25: DtypeWarning: Columns (17,25,35,37,40,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(f)

In [27]:
df4

,case_id,HHID,ea_id,region,district,reside,interviewDate,hh_wgt,hh_a02a,hh_a03,...,hh_a11,hh_a13,hh_a22,hh_a23,hh_g09,hh_m00,hh_o0a,hh_s01,hh_w01,hhsize
0,101011000014,7d78f2c5da59436d9bde9b09ea8a8aaf,10101100,North,Chitipa,RURAL,2019-08-29,93.719400,10101,100,...,NO,NaN,14,58,NO,Yes,YES,YES,NO,4
1,101011000023,7144cc6d29b3485d9e6d6188b255c756,10101100,North,Chitipa,RURAL,2019-08-29,93.719400,10101,100,...,NO,NaN,14,64,YES,Yes,YES,YES,NO,4
2,101011000040,9936d103bf974a93afbc63d477b8b3f2,10101100,North,Chitipa,RURAL,2019-08-28,93.719400,10101,100,...,NO,NaN,14,30,NO,Yes,NO,NO,NO,4
3,101011000071,cc8f211413cd493e83e01a96aba95bbb,10101100,North,Chitipa,RURAL,2019-08-29,93.719400,10101,100,...,NO,NaN,14,30,NO,Yes,YES,YES,NO,5
4,101011000095,e50cfa8d11b44d56891e0fad015b07c7,10101100,North,Chitipa,RURAL,2019-08-28,93.719400,10101,100,...,NO,NaN,14,58,NO,Yes,NO,YES,NO,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11429,315538160177,217455196b2e46a0996ca61da955e243,31553816,Southern,Blantyre City,URBAN,2020-01-27,607.988356,31553,816,...,YES,Dwelling found but no household member could b...,17,68,YES,Yes,NO,NO,NO,3
11430,315538160189,23707c4144fb489ab5482403274f396f,31553816,Southern,Blantyre City,URBAN,2020-01-24,607.988356,31553,816,...,NO,NaN,17,37,NO,No,NO,YES,NO,3
11431,315538160190,01d649e11c664fe580315f47328f99f8,31553816,Southern,Blantyre City,URBAN,2020-01-25,607.988356,31553,816,...,NO,NaN,17,69,YES,Yes,YES,NO,NO,1
11432,315538160235,80b809e8c90b49e88996ae340a532820,31553816,Southern,Blantyre City,URBAN,2020-01-25,607.988356,31553,816,...,NO,NaN,17,37,NO,No,NO,NO,NO,3
11433,315538160239,de477d97327c42a3804781971d0b90cf,31553816,Southern,Blantyre City,URBAN,2020-01-25,607.988356,31553,816,...,NO,NaN,17,69,NO,Yes,NO,NO,NO,1

In [28]:
# hh_b03        sex
# hh_e06_8a    economic activity did [NAME]spent most time in the last 12 months (ACT 1)

# main supposition: is that rows for df 1 and 3 are in the same order, so we can merge them on the index
df = pd.concat([df1[['case_id', 'PID', 'hh_e06_8a']], df3[['hh_b03']]], axis=1)
df = pd.pivot_table(df, index=['case_id', 'hh_b03'], columns=['hh_e06_8a'], aggfunc='size', fill_value=0).reset_index()
df = pd.merge(df, df4[['case_id', 'district', 'reside']], on='case_id', how='left')
df

,case_id,hh_b03,GANYU,HOUSEHOLD BUSINESS (NONAG),UNPAID APPRENTICESHIP,UNPAID HOUSEHOLD LABOR(AGRIC),WAGE EMPLOYMENT EXCLUDING GANYU,district,reside
0,101011000014,FEMALE,0,0,0,1,0,Chitipa,RURAL
1,101011000014,MALE,1,0,0,1,0,Chitipa,RURAL
2,101011000023,FEMALE,0,0,0,1,0,Chitipa,RURAL
3,101011000023,MALE,0,0,0,3,0,Chitipa,RURAL
4,101011000040,FEMALE,1,0,0,0,0,Chitipa,RURAL
...,...,...,...,...,...,...,...,...,...
19853,315538160189,MALE,0,1,0,0,0,Blantyre City,URBAN
19854,315538160190,MALE,0,0,0,0,1,Blantyre City,URBAN
19855,315538160235,FEMALE,0,1,0,0,0,Blantyre City,URBAN
19856,315538160235,MALE,0,1,0,0,0,Blantyre City,URBAN
19857,315538160239,MALE,1,0,0,0,0,Blantyre City,URBAN

### Filter the households used in the PCA

In [47]:
hh_id = pd.read_csv('../data/IHS_survey/household_data_IHS_case_id.csv')
hh_id

            case_id
0      101011000014
1      101011000023
2      101011000040
3      101011000040
4      101011000115
...             ...
10029  315538160190
10030  315538160190
10031  315538160235
10032  315538160235
10033  315538160239

[10034 rows x 1 columns]

In [52]:
df = df[df['case_id'].isin(hh_id['case_id'])]
df

,case_id,hh_b03,GANYU,HOUSEHOLD BUSINESS (NONAG),UNPAID APPRENTICESHIP,UNPAID HOUSEHOLD LABOR(AGRIC),WAGE EMPLOYMENT EXCLUDING GANYU,district,reside
0,101011000014,FEMALE,0,0,0,1,0,Chitipa,RURAL
1,101011000014,MALE,1,0,0,1,0,Chitipa,RURAL
2,101011000023,FEMALE,0,0,0,1,0,Chitipa,RURAL
3,101011000023,MALE,0,0,0,3,0,Chitipa,RURAL
4,101011000040,FEMALE,1,0,0,0,0,Chitipa,RURAL
...,...,...,...,...,...,...,...,...,...
19853,315538160189,MALE,0,1,0,0,0,Blantyre City,URBAN
19854,315538160190,MALE,0,0,0,0,1,Blantyre City,URBAN
19855,315538160235,FEMALE,0,1,0,0,0,Blantyre City,URBAN
19856,315538160235,MALE,0,1,0,0,0,Blantyre City,URBAN
19857,315538160239,MALE,1,0,0,0,0,Blantyre City,URBAN

In [59]:
# Step 1: Group by district and gender
gender_counts = df.groupby(['district', 'reside', 'hh_b03']).size().unstack(fill_value=0)

# Step 2: Calculate share of men and women
gender_share = gender_counts.div(gender_counts.sum(axis=1), axis=0)

# Step 3: Rename for clarity
gender_share = gender_share.rename(columns={
    'FEMALE': 'Share_Female',
    'MALE': 'Share_Male'
})

gender_share = gender_share.reset_index().set_index('district')
gender_share['reside'] = gender_share['reside'].str.lower()
# Final result
gender_share

hh_b03         reside  Share_Female  Share_Male
district
Balaka          rural      0.540359    0.459641
Balaka          urban      0.477273    0.522727
Blantyre        rural      0.554896    0.445104
Blantyre City   urban      0.417391    0.582609
Chikwawa        rural      0.527352    0.472648
Chikwawa        urban      0.500000    0.500000
Chiradzulu      rural      0.546032    0.453968
Chitipa         rural      0.511236    0.488764
Chitipa         urban      0.547619    0.452381
Dedza           rural      0.548387    0.451613
Dedza           urban      0.565217    0.434783
Dowa            rural      0.512755    0.487245
Dowa            urban      0.500000    0.500000
Karonga         rural      0.489736    0.510264
Karonga         urban      0.421687    0.578313
Kasungu         rural      0.516917    0.483083
Kasungu         urban      0.555556    0.444444
Likoma          rural      0.521739    0.478261
Lilongwe        rural      0.513699    0.486301
Lilongwe City   urban      0.434326    0.565674
Machinga        rural      0.555066    0.444934
Machinga        urban      0.615385    0.384615
Mangochi        rural      0.558824    0.441176
Mangochi        urban      0.419355    0.580645
Mchinji         rural      0.510081    0.489919
Mchinji         urban      0.470588    0.529412
Mulanje         rural      0.539503    0.460497
Mwanza          rural      0.551829    0.448171
Mwanza          urban      0.527778    0.472222
Mzimba          rural      0.528662    0.471338
Mzuzu City      urban      0.455764    0.544236
Neno            rural      0.532213    0.467787
Nkhatabay       rural      0.490506    0.509494
Nkhatabay       urban      0.600000    0.400000
Nkhotakota      rural      0.497608    0.502392
Nkhotakota      urban      0.357143    0.642857
Nsanje          rural      0.538106    0.461894
Nsanje          urban      0.538462    0.461538
Ntcheu          rural      0.548009    0.451991
Ntcheu          urban      0.521739    0.478261
Ntchisi         rural      0.525701    0.474299
Ntchisi         urban      0.461538    0.538462
Phalombe        rural      0.537988    0.462012
Rumphi          rural      0.472414    0.527586
Rumphi          urban      0.464286    0.535714
Salima          rural      0.524249    0.475751
Salima          urban      0.500000    0.500000
Thyolo          rural      0.557870    0.442130
Thyolo          urban      0.500000    0.500000
Zomba City      urban      0.504673    0.495327
Zomba Non-City  rural      0.549637    0.450363

In [61]:
occupation_share_men = gender_share[['reside', 'Share_Male']].copy()
occupation_share_women = gender_share[['reside', 'Share_Female']].copy()

In [62]:
occupation_share_men

hh_b03         reside  Share_Male
district
Balaka          rural    0.459641
Balaka          urban    0.522727
Blantyre        rural    0.445104
Blantyre City   urban    0.582609
Chikwawa        rural    0.472648
Chikwawa        urban    0.500000
Chiradzulu      rural    0.453968
Chitipa         rural    0.488764
Chitipa         urban    0.452381
Dedza           rural    0.451613
Dedza           urban    0.434783
Dowa            rural    0.487245
Dowa            urban    0.500000
Karonga         rural    0.510264
Karonga         urban    0.578313
Kasungu         rural    0.483083
Kasungu         urban    0.444444
Likoma          rural    0.478261
Lilongwe        rural    0.486301
Lilongwe City   urban    0.565674
Machinga        rural    0.444934
Machinga        urban    0.384615
Mangochi        rural    0.441176
Mangochi        urban    0.580645
Mchinji         rural    0.489919
Mchinji         urban    0.529412
Mulanje         rural    0.460497
Mwanza          rural    0.448171
Mwanza          urban    0.472222
Mzimba          rural    0.471338
Mzuzu City      urban    0.544236
Neno            rural    0.467787
Nkhatabay       rural    0.509494
Nkhatabay       urban    0.400000
Nkhotakota      rural    0.502392
Nkhotakota      urban    0.642857
Nsanje          rural    0.461894
Nsanje          urban    0.461538
Ntcheu          rural    0.451991
Ntcheu          urban    0.478261
Ntchisi         rural    0.474299
Ntchisi         urban    0.538462
Phalombe        rural    0.462012
Rumphi          rural    0.527586
Rumphi          urban    0.535714
Salima          rural    0.475751
Salima          urban    0.500000
Thyolo          rural    0.442130
Thyolo          urban    0.500000
Zomba City      urban    0.495327
Zomba Non-City  rural    0.450363

In [63]:
# Save the two DataFrame to a CSV file
occupation_share_men.to_csv(data_folder + 'employee_survey_men.csv')
occupation_share_women.to_csv(data_folder + 'employee_survey_women.csv')